config/routes.rb
M2s::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, path: '/', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }, controllers: { registrations: "store/visitors/registrations" }

  namespace :store do
    scope module: 'products' do
      get "dashboard/index"
      root 'dashboard#index'

      resources :categories, only: [:index, :show] do
        resources :entities, only: :show
      end
    end

    scope module: 'visitors' do
      resources :users, only: :show do
        resource :profile, except: [:index, :destroy]
      end
    end

    scope module: 'orders' do
      resources :cart_items, only: [:create, :destroy]
      resources :carts do
        get   'empty',                on: :collection
        get   'confirmation',         on: :member
        put   'create_confirmation',  on: :member
      end
    end
  end
  root to: 'store/products/dashboard#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  USERS_GENDER = { true: 'Мужской', false: 'Женский' }
  VALID_EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessor :login

  # Association macros
  # -----------------------------------------------------------
  has_one :profile, dependent: :destroy

  accepts_nested_attributes_for :profile, allow_destroy: true, reject_if: :all_blank

  # Validation macros
  # -----------------------------------------------------------
  validates :name,
            length:       { maximum: 50 },
            presence:     true,
            uniqueness:   { case_sensitive: false }
  validates :email,
            # allow_blank: true,
            presence:     true,
            uniqueness:   { case_sensitive: false },
            format:       { with: VALID_EMAIL_FORMAT }
  validates :password,
            length:       { minimum: 6 },
            presence:     true,
            on:           :create,
            confirmation: true

  # Devise
  # -----------------------------------------------------------
  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :trackable

  # Aliases
  # -----------------------------------------------------------
  delegate  :username,
            :phone,
            :skype,
            :url,
            :gender,
            :birthday,
            :timezone,
            :about,
            :address,
            to: :profile,
            prefix: true,
            allow_nil: true

  delegate :email_visible, to: :profile, allow_nil: true, prefix: false

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/store/visitors/application_controller.rb
class Store::Visitors::ApplicationController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/store/visitors/profiles_controller.rb
class Store::Visitors::ProfilesController < Store::Visitors::ApplicationController

  def new
    @profile = Profile.new(user_id: params[:user_id])
  end

  def create
    @profile = current_user.create_profile(profile_params)
    if @profile.save
      redirect_to root_url, notice: 'Your profile updated!'
    else
      flash[:error] = 'Error updating profile!' and render :new
    end
  end

  def show
    @profile = User.find(params[:user_id])
  end

  def edit
    @profile = current_user.profile
  end

  protected

    def profile_params
      params.require(:profile).permit!
    end
end

app/controllers/store/visitors/registrations_controller.rb
class Store::Visitors::RegistrationsController < Devise::RegistrationsController
  
  protected
  
    def after_sign_up_path_for(resource)
      new_store_user_profile_path(user_id: @user)
    end

end

app/controllers/store/visitors/users_controller.rb
class Store::Visitors::UsersController < Store::Visitors::ApplicationController
  def show
    if current_user.id == params[:id]
      @user = current_user
    else
      @user = User.find(params[:id])
    end
  end
end

app/views/store/visitors/users/show.html.haml
- model_class = Profile
.span12
  .page-header
    %h3= "#{t '.title'} '#{@user.name}'"
  %ul.nav.nav-tabs
    %li.active
      = link_to 'Пользователь', '#user', data: {toggle: 'tab'}

    %li
      = link_to 'Профиль', '#profile', data: {toggle: 'tab'}

  .tab-content#myTabContent
    .tab-pane.fade.active.in#user
      .span2
        %ul.thumbnails
          %li= link_to image_tag(rescue_user_avatar(current_user.profile ? current_user.profile.avatar : nil), size: "100x100"), '#', class: 'thumbnail'
      .span4
        %strong= t '.login'
        = @user.name
        %br
        - if @user.email_visible || @user.id = current_user.id
          %strong= t '.email'
          = @user.email
          %br
        - else
          = t '.no_email_visible'
        - if @user.profile
          %strong= t '.username'
          = rescue_empty_value @user.username
          %br
    .tab-pane.fade#profile
      - if @user.profile
        %p
          %strong= t '.username'
          = @profile.username if @profile
        %p
          - if current_user.profile && current_user.profile.email_visible
            %strong= t '.email'
            = current_user.email
            %br
          %strong= t '.email_visible_label'
          .badge.badge-important= yes_or_no @profile.email_visible if @profile
        %p
          %strong= t '.birthday'
          = @profile.birthday if @profile
        %p
          %strong= model_class.human_attribute_name(:address)
          = @profile.address.values.join('/') if @profile
        %p
          %strong= model_class.human_attribute_name(:gender)
          = gender @profile.gender if @profile
        %p
          %strong= model_class.human_attribute_name(:about)
          .well= @profile.about if @profile
        .panel.panel-default
          .panel-body
            %strong= model_class.human_attribute_name(:phone)
          .panel-footer
            = @profile.about if @profile
        %p
          %strong= model_class.human_attribute_name(:skype)
          %br
          = @profile.skype if @profile
        %p
          %strong= model_class.human_attribute_name(:url)
          %br
          = @profile.url if @profile
        %p
          %strong= model_class.human_attribute_name(:time_zone)
          %br
          = @profile.time_zone if @profile
      - else
        .well= t '.user_profile_not_exists', user: @user.name

  .form-actions
    = link_to t('.back'), :back, :class => 'btn'
    - if @user.profile
      = link_to t('.edit'), edit_store_user_profile_path(@user, @user.profile), :class => 'btn'
    - else
      = link_to t('.edit'), new_store_user_profile_path(@user), :class => 'btn btn-primary'