config/routes.rb
M2s::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, path: '/', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }, controllers: { registrations: "store/visitors/registrations" }

  namespace :store do
    scope module: 'products' do
      get "dashboard/index"
      root 'dashboard#index'

      resources :categories, only: [:index, :show] do
        resources :entities, only: :show
      end
    end

    scope module: 'visitors' do
      resources :users, only: :show do
        resource :profile, except: [:index, :destroy]
      end
    end

    scope module: 'orders' do
      resources :cart_items, only: [:create, :destroy]
      resources :carts do
        get   'empty',                on: :collection
        get   'confirmation',         on: :member
        put   'create_confirmation',  on: :member
      end
    end
  end
  root to: 'store/products/dashboard#index'
end

app/models/entity.rb
class Entity < ActiveRecord::Base
  include DataHandler

  # Association macros
  # -----------------------------------------------------------
  belongs_to :category
  belongs_to :manufacturer
  belongs_to :currency

  has_and_belongs_to_many :features
  
  has_many :entity_properties, class_name: 'Attribute', through: :parameters
  has_many :cart_items

  with_options dependent: :destroy do |association|
    association.has_many :parameters
  end

  accepts_nested_attributes_for :parameters

  # Validation macros
  # -----------------------------------------------------------
  validates :title,
            presence:     true,
            length:       { maximum: 255 },
            uniqueness:   { case_sensitive: false }
  validates :price,
            numericality: { greater_than_or_equal_to: 0 }
  validates :availability, :guarantee,
            numericality: { greater_than_or_equal_to: 0, only_integer: true },
            allow_blank:  true

  # Aliases
  # -----------------------------------------------------------
  delegate :properties,             to: :category, prefix: true
  delegate :parent_category,        to: :category, allow_nil: true
  delegate :abbreviation, :emblem,  to: :currency, prefix: true

  # Callbacks
  # -----------------------------------------------------------
  before_save     :set_characteristics_from_parameters_attributes
  before_create   :input_data_handle, on: :create
  before_destroy  :check_reference_any_cart_item

  # Scopes
  # -----------------------------------------------------------
  scope :published,       -> { where(published: true) }
  scope :unpublished,     -> { where(published: false) }
  scope :expensive,       -> { published.unscope(:order).order('price DESC') }
  scope :cheap,           -> { published.unscope(:order).order('price') }

  # CarrierWave
  # -----------------------------------------------------------
  mount_uploader :cover, EntityUploader

  def to_param
    # "#{id}-#{title.parametrize}"
  end

  def save(*)
    set_product_currency
    super
  end

  # Class methods
  # -----------------------------------------------------------
  protected

    def set_characteristics_from_parameters_attributes
      self.characteristics = self.parameters.map { |p| p.value.to_s + p.attribute.unit.try(:param).to_s }.join(" / ")
    end

    def input_data_handle
      self.title = self.title.squish.truncate(255)
      self.description = safe_txt self.description
    end

    def set_product_currency
      self.currency_id ||= Currency.main
    end

    def check_reference_any_cart_item
      unless cart_items.empty?
        errors.add(:base, 'Cуществуют товарные позиции c этим товаром')
        return false
      end
    end
end

app/controllers/store/products/categories_controller.rb
class Store::Products::CategoriesController < ApplicationController
  def index
    @categories = Category.for_index
  end

  def show
    category = Category.find(params[:id])
    @category_decorator = CategoryDecorator.new(category)
  end
end

app/controllers/store/products/dashboard_controller.rb
class Store::Products::DashboardController < ApplicationController
  def index
  end
end

app/controllers/store/products/entities_controller.rb
# rails g controller Entities index show --no-helper --no-assets --no-view-specs
class Store::Products::EntitiesController < ApplicationController
  def show
    entity = Entity.find(params[:id])
    entity.increment! :views
    @presenter = Entities::ShowPresenter.new(entity)
  end
end

app/views/store/products/entities/_entity.html.haml
%ul.thumbnails
  %li.span4
    .thumbnail.skip-border
      %h3.panel-title= link_to entity.title, store_category_entity_path(entity.category, entity.id)
      = button_to '+ Добавить в корзину', store_cart_items_path(entity_id: entity.id), class: "btn btn-success btn-small"
      = link_to image_tag('/defaults/wave.png')#, category_path(category), class: 'thumbnail'
      .pull-right
        .text-left
          %b.text-info Цена:
          %h2.text-success= readable_price entity.price
          %span.badge.badge-success= entity.currency_abbreviation
      %p.muted
        %br
        = entity.characteristics
      %p.text-right= link_to "Подробнее...", store_category_entity_path(entity.category, entity.id)

app/views/store/products/entities/_show_header.html.haml
/ Header
.muted Категория:
- if @presenter.parent?
  %span #{link_to main.title, store_category_path(main)} / #{link_to secondary.title, store_category_path(secondary)}

app/views/store/products/entities/_show_product.html.haml
/ Product section
.text-success Товарная позиция:
%h2.text-success= product.title
Код товара:
%span.badge.badge-success= product.id
%hr
/ Section preview product
.container
  .span4
    = link_to product_cover(product.cover.large_preview.url), "#", class: "thumbnail"
    %p.text-success= product_availability(product.availability)
    - unless product.feature_ids.empty?
      %p.muted Особенности:
      - product.features.each do |feature|
        = image_tag feature.label_url, alt: feature.name, title: feature.name
  .span3
    %h1.text-success #{product.price.to_s(:rounded, precision: 2)} #{image_tag product.currency_emblem.url}
    = button_to 'Купить', store_cart_items_path(entity_id: product.id), class: "btn btn-success btn-large"
    %br
    %br
    %p.muted= product.characteristics
/ section view product tabs
%h2#nav-tabs О товаре:
%ul.nav.nav-tabs
  %li.active
    %a{data: {toggle: "tab"}, href: "#home"}
      Всё
  %li
    %a{data: {toggle: "tab"}, href: "#char"}
      Характеристики
  %li
    %a{data: {toggle: "tab"}, href: "#foto"}
      Фото
  %li
    %a{data: {toggle: "tab"}}
      Отзывы
  %li
    %a{data: {toggle: "tab"}}
      Аксессуары
.tab-content#myTabContent
  .tab-pane.fade.active.in#home
    %p= product.description
  .tab-pane.fade#char
    %h1 Характеристики:
    %hr
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Характеристика:
          %th Значение:
      %tbody
        - product.parameters.each do |param|
          %tr
            %td= param.attribute.name
            %td= param.value + " " + param.attribute.unit.try(:param).to_s
  .tab-pane.fade#foto
    = product.cover? ? image_tag(product.cover.url) : content_tag(:p, "Фото товара отсутствует", class: "muted" )
%a{href: "#"}
  Просмотров:
  %span.badge.badge-info= product.views
%br
%br

app/views/store/products/entities/_show_sidebars.html.haml
%ul.list-group
  = link_to @presenter.main_category.title + ":", store_category_path(@presenter.main_category), class: "list-group-item active"
  - @presenter.related_categories.each do |c|
    %li.list-group-item
      = link_to c.title, store_category_path(c)
      %span.badge= c.entities.size
%ul.list-group
  = link_to "Доставка", "#", class: "list-group-item active"
  %li.list-group-item
    Информация о доставке!

app/views/store/products/entities/show.html.haml
/ Product section
.span9
  / Page header
  = render partial: "show_header", locals: { main: @presenter.main_category, secondary: @presenter.sub_category }
  / Product info
  = render partial: "show_product", locals: { product: @presenter.product }
/ Sidebar
.span3
  = render "show_sidebars"