config/routes.rb
M2s::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, path: '/', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }, controllers: { registrations: "store/visitors/registrations" }

  namespace :store do
    scope module: 'products' do
      get "dashboard/index"
      root 'dashboard#index'

      resources :categories, only: [:index, :show] do
        resources :entities, only: :show
      end
    end

    scope module: 'visitors' do
      resources :users, only: :show do
        resource :profile, except: [:index, :destroy]
      end
    end

    scope module: 'orders' do
      resources :cart_items, only: [:create, :destroy]
      resources :carts do
        get   'empty',                on: :collection
        get   'confirmation',         on: :member
        put   'create_confirmation',  on: :member
      end
    end
  end
  root to: 'store/products/dashboard#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  VALID_USERNAME_FORMAT = /[[:alpha:]. -]+\z/i
  VALID_PHONE_FORMAT = /[\d()-]+/i

  serialize :cart_info, Hash

  # Association macros
  # -----------------------------------------------------------
  has_many :cart_items, dependent: :destroy

  # Validation macros
  # -----------------------------------------------------------

  validate  :cart_info_validate_username,
            :cart_info_validate_phone,
            :cart_info_validate_street,
            on: :update

  validate :cart_info_validate_true_username, if: lambda{ cart_info[:username].present? }
  validate :cart_info_validate_true_phone,    if: lambda{ cart_info[:phone].present? }

  def is_hash?
    cart_info.is_a(Hash)
  end

  def cart_info_validate_username
    presence_validate cart_info[:username], I18n.t('.carts.fields.ci_username')
  end

  def cart_info_validate_phone
    presence_validate cart_info[:phone], I18n.t('.carts.fields.ci_phone')
  end

  def cart_info_validate_street
    presence_validate cart_info[:street], I18n.t('.carts.fields.ci_street')
  end

  def cart_info_validate_true_username
    unless cart_info[:username] =~ VALID_USERNAME_FORMAT
      errors.add(I18n.t('.carts.fields.ci_username'), I18n.t('.carts.error_messages.ci_username_real'))
    end
  end

  def cart_info_validate_true_phone
    unless cart_info[:phone] =~ VALID_PHONE_FORMAT
      errors.add(I18n.t('.carts.fields.ci_phone'), I18n.t('.carts.error_messages.ci_phone_real'))     
    end
  end

  def presence_validate data, field_name = ''
    if data.try(:squish).blank?
      errors.add(field_name, I18n.t('.carts.error_messages.ci_presence'))
    end
  end

  # Scopes
  # -----------------------------------------------------------
  scope :confirmed_by_user, ->{ where(user_confirmation:true) }
  scope :preorders,         ->{ confirmed_by_user.where(admin_user_confirmation: false) }
  scope :orders,            ->{ confirmed_by_user.where(admin_user_confirmation: true) }
  scope :empty_orders,      ->{ where("user_confirmation = ? AND created_at = ?",
                                      false, Time.now.midnight - 1.day) }

  # Instance methods
  # -----------------------------------------------------------
  def add_product(product_id)
    current_item = cart_items.find_by(entity_id: product_id)
    if current_item
      current_item.increment!(:quantity)
    else
      current_item = cart_items.build(entity_id: product_id)
    end
    current_item
  end

  def total_cart_price
    cart_items.to_a.sum { |item| item.total_item_price }
  end
end

app/controllers/store/orders/cart_items_controller.rb
# rails g controller cart_items --no-helper --no-assets --no-view-specs
class Store::Orders::CartItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: [:create]

  def create
    product = Entity.find(params[:entity_id])
    @cart_item = @cart.add_product(product.id)
    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to store_cart_url(@cart_item.cart), notice: 'Product was successfully added to cart.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to store_cart_url(session[:cart_id]), notice: 'Товарная позиция удаленна!' }
    end
  end

  def cart_item_params
    params.require(:cart_item).permit(:entity_id)
  end
end

app/controllers/store/orders/carts_controller.rb
# rails g controller carts --no-helper --no-assets --no-view-specs
class Store::Orders::CartsController < ApplicationController

  before_filter only: [:destroy, :show, :confirmation, :create_confirmation] { |m| m.get_cart_by_id(params[:id]) }

  rescue_from ActiveRecord::RecordNotFound, with: :null_cart

  def show
    render 'empty' if @cart.try(:cart_items).blank?
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: t('.cart_clear') }
    end
  end

  def empty
  end

  def confirmation
  end

  def create_confirmation
    @cart.user_confirmation = true if @cart
    if @cart.update_attributes(cart_params)
      session[:cart_id] = nil
      redirect_to root_url, notice: t('.sucess_confirmation')
    else
      flash.now[:error] = t('.invalid_cart_form')
      render :confirmation
    end
  end

  protected

    def null_cart
      logger.error t('.logger_error_access_cart', id: params[:id])
      redirect_to store_categories_url, notice: t('.no_cart_isset')
    end

    def get_cart_by_id id
      @cart = Cart.find id
    end

    def cart_params
      params.require(:cart).permit(cart_info: [:username, :street, :note, :city, :phone])
    end
end

app/views/store/orders/carts/_form.html.haml
= simple_form_for @cart, url: create_confirmation_store_cart_path(params[:id]), method: :put, html: { class: 'form-horizontal' } do |f|
  %fieldset
    %legend= t('.confirmation_legend')
    %hr
    = render 'common/errors', object: @cart if @cart.errors.any?
    .control-group
      = f.simple_fields_for :cart_info do |subform|
        .control-group
          = subform.input :username, label: t('.confirmation_username'), placeholder: 'Ваше имя...'
        .control-group
          = subform.input :phone, label: t('.confirmation_phone'), placeholder: '(xxx) - xxx - xx - xx'
        .control-group
          = subform.input :note, as: :text, label: t('.confirmation_note'), placeholder: '...', input_html: {rows: 10, cols: 20 }
        .control-group
          = subform.input :city, label: t('.confirmation_city'), collection: ['Москва', 'Казань', 'Ростов-на-дону', 'Курск', 'Орел', 'Екатеринбург', 'Калининград', 'Челябинск', 'Сочи', 'Мурманск', 'Симферополь', 'Севастополь', 'Санкт-Петербург', 'Волгоград'], include_blank:false
        .control-group
          = subform.input :street, label: t('.confirmation_street')
    .form-actions
      = f.button :submit, 'Подтвердить', class: 'btn btn-success btn-large'
      = link_to 'Отменить', store_cart_path(@cart), :class => 'btn btn-large'

app/views/store/orders/carts/confirmation.html.haml
- provide(:title, 'Оформление заказа')
/ Cart confirmation
.span9
  %h2.text-primary Оформление заказа:
  %p.text-warning * Заполните ВСЕ предложенные Вам поля!
  = render 'form'

app/views/store/orders/carts/empty.html.haml
- provide(:title, 'Корзина покупателя')
/ Cart
.span9
  %h2.text-primary Ваша корзина пуста:
  %h2.text-info Выберите товар, перейдя по ссылке ниже, чтобы добавить товар в корзину #{ link_to 'Добавить товар в корзину', store_categories_path, class: 'btn btn-info' }
  %p
    %b= link_to "Вернуться на главную", root_url

app/views/store/orders/carts/show.html.haml
- provide :title, t('.customer_cart')
/ Cart
.span9
  %h2.text-primary Ваша корзина:
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th #
        %th Кол-во:
        %th Цена за 1 ед.:
        %th Наименование товара:
        %th Конечная Цена:
        %th Действие:
    %tbody
      - @cart.cart_items.each_with_index do |item, index|
        %tr
          %td= index.next
          %td #{item.quantity} &times;
          %td= readable_price item.entity_price
          %td
            %b= link_to item.entity_title, store_category_entity_path(item.entity_category_id, item.entity_id)
          %td
            %b.text-success
              = readable_price item.total_item_price
            %span.badge.badge-success
              = item.entity_currency.abbreviation
          %td= link_to "Удалить", store_cart_item_path(item), method: :delete#, data: { confirm: t('.confirm_deletion_item', entity: item.entity_title) }
      %tr
        %td{colspan: 4}
          %br
          %b Всего:
        %td
          %h3.text-success
            = readable_price @cart.total_cart_price
        %td
          %br
          = button_to 'Очистить корзину', store_cart_path(@cart), method: :delete, class: "btn btn-danger"#, data: { confirm: t('.confirm_deletion_cart') }
  %p.centered
    = link_to 'Оформить заказ', confirmation_store_cart_path(@cart), class: 'btn btn-success btn-large'