config/routes.rb
M2s::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  devise_for :users, path: '/', path_names: { sign_in: 'signin', sign_up: 'signup', sign_out: 'signout' }, controllers: { registrations: "store/visitors/registrations" }

  namespace :store do
    scope module: 'products' do
      get "dashboard/index"
      root 'dashboard#index'

      resources :categories, only: [:index, :show] do
        resources :entities, only: :show
      end
    end

    scope module: 'visitors' do
      resources :users, only: :show do
        resource :profile, except: [:index, :destroy]
      end
    end

    scope module: 'orders' do
      resources :cart_items, only: [:create, :destroy]
      resources :carts do
        get   'empty',                on: :collection
        get   'confirmation',         on: :member
        put   'create_confirmation',  on: :member
      end
    end
  end
  root to: 'store/products/dashboard#index'
end

app/views/common/_errors.html.haml
.alert
  %h4 There are (#{object.errors.count}) errors exists :"
  .error-wrap
    - object.errors.full_messages.each do |msg|
      .error= msg

app/views/common/_footer.html.haml
.container
  %p.muted.credits
    &copy; Wave
    = DateTime.now.year

app/views/common/_header.html.haml
.navbar-inner
  .container
    %a.brand{ href: '#' }
      Brand
    .nav-collapse
      %ul.nav.navbar-nav
        %li.active.dropdown
          %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
            Выбрать раздел
            %b.caret
          %ul.dropdown-menu
            - Category.parental.each do |p|
              %li= link_to p.title, store_category_path(p)
        %li= link_to "Мои покупки (#{cart_size(session[:cart_id])})", session[:cart_id].nil? ? empty_store_carts_path : store_cart_path(session[:cart_id])
        %li.dropdown
          %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
            = user_signed_in? ? current_user.name : 'Войти'
            %b.caret
          - if user_signed_in?
            %ul.dropdown-menu
              %li= link_to "Выйти(#{current_user.name})", destroy_user_session_path
              %li= link_to "Профиль", store_user_path(current_user.id)
              %li= link_to "Редактировать", edit_user_registration_path
          - else
            %ul.dropdown-menu
              %li= link_to "Представиться", new_user_session_path
              %li= link_to "Присоединиться", new_user_registration_path
      %form.navbar-form.navbar-left
        %input.form-control.col-lg-8{ placeholder: "Search", type: "text" }

app/views/common/_navigate.html.haml
%ul.nav.nav-pills.nav-stacked
  %li.active= link_to "Все Категории ->", store_categories_path
  %li.divider
  - get_all_active_categories.each do |category|
    - if category.subcategories.empty?
      %li= link_to category.title, store_category_path(category)
    -else
      %li.dropdown
        %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}}
          = category.title
          %span.caret
        %ul.dropdown-menu
          - category.subcategories.each do |subcategory|
            %li= link_to subcategory.title, store_category_path(subcategory)

app/views/common/_notice.html.haml
.container
  - flash.each do |key,value|
    .p= content_tag(:div, "Сообщение: #{value}", class: "alert alert-#{key} span8 offset2")